export const PSYCHOLOGICAL_FACTS = [
  "The 'Placebo Effect' works even when you know it's a placebo. Your brain still releases feel-good chemicals.",
  "Your brain treats rejection like physical pain. The same areas of the brain light up in an MRI.",
  "Singing reduces feelings of anxiety and depression by releasing endorphins and oxytocin.",
  "Crying makes you feel better, reduces stress, and may help to keep the body healthy by flushing out toxins.",
  "If you announce your goals to others, you are less likely to make them happen because you lose motivation.",
  "The average person has 3 to 5 best friends and usually hates one person in their social group.",
  "People who speak two languages may unconsciously change their personalities when they switch from one language to another.",
  "Being alone for a long time is as bad for your health as smoking 15 cigarettes a day.",
  "You’re more creative when you’re tired. Your brain struggles to filter out 'distracting' creative thoughts.",
  "It only takes 4 minutes to fall in love. It's a chemical reaction similar to being on drugs.",
  "90% of people text things they can't say in person. The screen provides a safety barrier.",
  "Smart people tend to have fewer friends than the average person. The smarter the individual, the more selective they become.",
  "The type of music you listen to affects the way you perceive the world and your emotional state.",
  "People who spend more time in the sun are likely to be happier due to Vitamin D and serotonin production.",
  "Pretending not to care is the habit of someone who generally cares the most. It's a defense mechanism.",
  "Your brain does more creative work when you are sleepy because your internal filters are relaxed.",
  "The more you spend on others, the happier you feel. Generosity triggers the brain's reward system.",
  "Thinking that something bad will happen is actually more stressful than something bad actually happening.",
  "Most people have a 'favorite' song because they associate it with an emotional event in their life.",
  "Memories are more like creative fiction than a recorded video. Every time you recall one, it changes slightly.",
  "We can only be close to about 150 people. This is known as Dunbar's Number, based on brain size.",
  "When you remember a past event, you are actually remembering the last time you remembered it, not the event itself.",
  "Decisions are more rational when thought in another language because it removes emotional bias.",
  "Your pupil dilates up to 45% when you look at someone you love. It's an involuntary physical response.",
  "The 'Dunning-Kruger Effect' makes incompetent people think they are amazing, while experts often doubt themselves."
];
